credentials:
  system:
    domainCredentials:
      - credentials:
        - string:
            scope: GLOBAL
            id: github-coreosbot-token
            secret: ${github-coreosbot-token/token}
            description: GitHub coreosbot token
